name: 'Language Detection'
description: 'Detect the primary language used in a issue, comment or pull request.'
author: 'Chronophylos'
inputs:
  input:
    description: 'input text'
    required: true
  output:
    description: 'Name of the environment variable to set to the detected language code'
    default: 'language'
runs:
  using: 'node12'
  main: 'dist/index.js'
