name: 'comment-test'
on:
  issue_comment:
    types: [created]
  #issues:
  # types: [opened]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Dump comment event'
        run: echo "${{toJson(github.event.comment)}}"
      - uses: ./
        id: 'detect'
        with:
          input: '${{github.event.comment.body}}'
      - name: 'Dump result'
        run: echo "Found language `${{steps.detect.outputs.language}}`"
